apiVersion: v1
kind: PersistentVolume
metadata:
  name: cloud-psql-pv
  namespace: cloud
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /home/files/.cloud
    server: 192.168.86.100
  storageClassName: cloud-psql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-psql-pvc
  namespace: cloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: cloud-psql-pv
  storageClassName: cloud-psql
