apiVersion: v1
kind: PersistentVolume
metadata:
  name: docmost-data-pv
  namespace: docmost
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /srv/data/docmost/data
    server: 192.168.86.100
  storageClassName: docmost-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: docmost-psql-pv
  namespace: docmost
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /srv/data/docmost/psql
    server: 192.168.86.100
  storageClassName: docmost-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: docmost-redis-pv
  namespace: docmost
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /srv/data/docmost/redis
    server: 192.168.86.100
  storageClassName: docmost-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docmost-data-pvc
  namespace: docmost
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: docmost-data-pv
  storageClassName: docmost-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docmost-psql-pvc
  namespace: docmost
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: docmost-psql-pv
  storageClassName: docmost-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docmost-redis-pvc
  namespace: docmost
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: docmost-redis-pv
  storageClassName: docmost-data
---
