apiVersion: v1
kind: PersistentVolume
metadata:
  name: distributed-streaming-music
  namespace: distributed-streaming
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /srv/music
    server: 192.168.86.100
  storageClassName: distributed-streaming-music
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: distributed-streaming-music
  namespace: distributed-streaming
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: distributed-streaming-music
  storageClassName: distributed-streaming-music
