apiVersion: apps/v1
kind: Deployment
metadata:
  name: sso-login
  namespace: sso
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sso-login
  template:
    metadata:
      labels:
        app: sso-login
    spec:
      containers:
      - name: sso-login
        image: docker.prayujt.com/sso-login
        ports:
        - containerPort: 3000
        env:
        - name: HYDRA_ADMIN_URL
          value: "http://hydra-admin.hydra.svc.cluster.local:4445"
        - name: KRATOS_ADMIN_URL
          value: "http://kratos-admin.kratos.svc.cluster.local"
        - name: KRATOS_PUBLIC_URL
          value: "https://idp.prayujt.com"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/arch"
                operator: In
                values:
                - arm64
---
apiVersion: v1
kind: Service
metadata:
  name: sso-login
  namespace: sso
spec:
  selector:
    app: sso-login
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
