apiVersion: v1
kind: PersistentVolume
metadata:
  name: ethereum-pv-geth
  namespace: eth
spec:
  capacity:
    storage: 150Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /srv/ethereum/geth
  storageClassName: ethereum-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - server-master
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ethereum-pv-lighthouse
  namespace: eth
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /srv/ethereum/lighthouse
  storageClassName: ethereum-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - server-master
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ethereum-pvc-geth
  namespace: eth
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 150Gi
  volumeName: ethereum-pv-geth
  storageClassName: ethereum-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ethereum-pvc-lighthouse
  namespace: eth
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: ethereum-pv-lighthouse
  storageClassName: ethereum-data
