apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-ingress
  namespace: hydra
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/client-max-body-size: "2g"
    nginx.ingress.kubernetes.io/proxy-body-size: "2g"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/configuration-snippet: |
      set $cors_origin '';
      if ($http_origin ~* (https?://(?:.*\.)?prayujt\.com(:[0-9]+)?)$) {
          set $cors_origin $http_origin;
      }
      more_set_headers 'Access-Control-Allow-Origin: $cors_origin';
      more_set_headers 'Access-Control-Allow-Methods: GET, POST, OPTIONS';
      more_set_headers 'Access-Control-Allow-Headers: Authorization, Cookie, Origin, Content-Type, Accept, X-Csrf-Token';
      more_set_headers 'Access-Control-Expose-Headers: Content-Type, Set-Cookie';
      more_set_headers 'Access-Control-Allow-Credentials: true';
spec:
  tls:
  - hosts:
    - auth.prayujt.com
    secretName: auth-prayujt-certs
  rules:
  - host: auth.prayujt.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hydra-public
            port:
              number: 4444
