apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: hydra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "hydra_db"
        - name: POSTGRES_USER
          value: "hydra_user"
        - name: POSTGRES_PASSWORD
          value: "hydra_password"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: idp-psql
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: hydra
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
