apiVersion: v1
kind: PersistentVolume
metadata:
  name: hydra-postgres-pv
  namespace: hydra
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /srv/data/hydra
  storageClassName: hydra-postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - server-master
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hydra-postgres-pvc
  namespace: hydra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: hydra-postgres-pv
  storageClassName: hydra-postgres
