apiVersion: v1
kind: PersistentVolume
metadata:
  name: idp-psql
  namespace: hydra
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /home/files/.hydra-users
    server: 192.168.86.100
  storageClassName: idp-psql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: idp-psql
  namespace: hydra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: idp-psql
  storageClassName: idp-psql
