apiVersion: v1
kind: Service
metadata:
  name: hue-control
  namespace: hue-control
spec:
  type: ClusterIP
  selector:
    app: hue-control
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
