apiVersion: v1
kind: PersistentVolume
metadata:
  name: mqtt-pv
  namespace: mqtt
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /home/files/.mqtt
    server: 192.168.86.100
  storageClassName: mqtt-volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mqtt-pvc
  namespace: mqtt
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: mqtt-pv
  storageClassName: mqtt-volume
