apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-nfs-pv
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: gitea
    meta.helm.sh/release-namespace: gitea
  namespace: gitea
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /home/files/.gitea
    server: 192.168.86.100
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-nfs-pvc
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: gitea
    meta.helm.sh/release-namespace: gitea
  namespace: gitea
spec:
  volumeName: gitea-nfs-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

