apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: server-master
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - master
      containers:
      - name: pihole
        image: pihole/pihole:latest
        ports:
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        - containerPort: 67
          name: dhcp
          protocol: UDP
        - containerPort: 8001
          name: web
          protocol: TCP
        env:
        - name: TZ
          value: "America/New_York"
        - name: CORS_HOSTS
          value: "dns.prayujt.com,prayujt.com"
        - name: WEB_PORT
          value: "8001"
        - name: PIHOLE_DNS_
          value: "1.1.1.1,1.0.0.1"
        - name: INTERFACE
          value: "enp3s0"
        - name: WEBPASSWORD
          valueFrom:
            secretKeyRef:
              name: pihole-web-password
              key: password
        volumeMounts:
        - name: etc-pihole
          mountPath: /etc/pihole
        - name: etc-dnsmasq
          mountPath: /etc/dnsmasq.d
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
      volumes:
      - name: etc-pihole
        persistentVolumeClaim:
          claimName: pihole-config-pvc
      - name: etc-dnsmasq
        persistentVolumeClaim:
          claimName: pihole-dnsmasq-pvc
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns
  namespace: pihole
spec:
  type: ClusterIP
  selector:
    app: pihole
  ports:
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: dhcp
      port: 67
      targetPort: 67
      protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-web
  namespace: pihole
spec:
  type: ClusterIP
  selector:
    app: pihole
  ports:
    - name: web
      port: 8001
      targetPort: 8001
      protocol: TCP
