apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-config-pv
  namespace: pihole
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /home/files/.pihole/config
    server: 192.168.86.100
  storageClassName: pihole-config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-dnsmasq-pv
  namespace: pihole
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /home/files/.pihole/dnsmasq
    server: 192.168.86.100
  storageClassName: pihole-dnsmasq
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-config-pvc
  namespace: pihole
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pihole-config-pv
  storageClassName: pihole-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-dnsmasq-pvc
  namespace: pihole
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pihole-dnsmasq-pv
  storageClassName: pihole-dnsmasq
