apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-config-pv
  namespace: pihole
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /srv/data/pihole/config
    server: 192.168.86.100
  mountOptions:
    - vers=4.1
    - hard
    - noatime
  storageClassName: pihole-config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-dnsmasq-pv
  namespace: pihole
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /srv/data/pihole/dnsmasq
    server: 192.168.86.100
  storageClassName: pihole-dnsmasq
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-config-pvc
  namespace: pihole
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: pihole-config-pv
  storageClassName: pihole-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-dnsmasq-pvc
  namespace: pihole
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pihole-dnsmasq-pv
  storageClassName: pihole-dnsmasq
