apiVersion: apps/v1
kind: Deployment
metadata:
  name: navidrome
  namespace: navidrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: navidrome
  template:
    metadata:
      labels:
        app: navidrome
    spec:
      containers:
      - name: navidrome
        image: deluan/navidrome:latest
        ports:
        - containerPort: 4533
        env:
        - name: ND_SCANSCHEDULE
          value: "1h"
        - name: ND_LOGLEVEL
          value: "info"
        - name: ND_SESSIONTIMEOUT
          value: "24h"
        - name: ND_BASEURL
          value: ""
        - name: ND_CONFIGFILE
          value: "/data/navidrome.toml"
        - name: ND_LASTFM_APIKEY
          valueFrom:
            secretKeyRef:
              name: navidrome-env
              key: LASTFM_API_KEY
        - name: ND_LASTFM_SECRET
          valueFrom:
            secretKeyRef:
              name: navidrome-env
              key: LASTFM_SECRET
        - name: ND_SPOTIFY_ID
          valueFrom:
            secretKeyRef:
              name: navidrome-env
              key: SPOTIFY_CLIENT_ID
        - name: ND_SPOTIFY_SECRET
          valueFrom:
            secretKeyRef:
              name: navidrome-env
              key: SPOTIFY_SECRET
        - name: ND_ENABLESHARING
          valueFrom:
            secretKeyRef:
              name: navidrome-env
              key: ENABLE_SHARING
        volumeMounts:
        - name: data
          mountPath: /data
        - name: music
          mountPath: /music
          readOnly: true
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: music-data-nfs-pvc
      - name: music
        persistentVolumeClaim:
          claimName: music-nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: navidrome-service
  namespace: navidrome
spec:
  selector:
    app: navidrome
  ports:
  - protocol: TCP
    port: 4533
    targetPort: 4533
