apiVersion: v1
kind: PersistentVolume
metadata:
  name: music-nfs-pv
  namespace: navidrome
spec:
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /srv/music
    server: 192.168.86.100
  storageClassName: navidrome-music
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: music-data-nfs-pv
  namespace: navidrome
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /srv/data/navidrome
    server: 192.168.86.100
  storageClassName: navidrome-music
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-nfs-pvc
  namespace: navidrome
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
  volumeName: music-nfs-pv
  storageClassName: navidrome-music
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-data-nfs-pvc
  namespace: navidrome
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: music-data-nfs-pv
  storageClassName: navidrome-music

