apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse
  namespace: matrix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synapse-server
  template:
    metadata:
      labels:
        app: synapse-server
    spec:
      initContainers:
      - name: init-permissions
        image: busybox
        command: ['sh', '-c', 'chmod -R 777 /data']
        volumeMounts:
        - name: synapse-data
          mountPath: /data
      containers:
      - name: synapse-server
        image: docker.io/matrixdotorg/synapse:latest
        securityContext:
          runAsUser: 0
        env:
        - name: SYNAPSE_CONFIG_PATH
          value: /data/homeserver.yaml
        volumeMounts:
        - name: synapse-data
          mountPath: /data
        ports:
        - containerPort: 8008
        - containerPort: 8448
        resources:
          requests:
            memory: "2Gi"
          limits:
            memory: "4Gi"
              #livenessProbe:
              #httpGet:
              #path: /_matrix/client/versions
              #port: 8008
              #initialDelaySeconds: 30
              #periodSeconds: 10
              #readinessProbe:
              #httpGet:
              #path: /_matrix/client/versions
              #port: 8008
              #initialDelaySeconds: 30
              #periodSeconds: 10
      volumes:
      - name: synapse-data
        persistentVolumeClaim:
          claimName: synapse-server-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: synapse-server
  namespace: matrix
spec:
  selector:
    app: synapse-server
  ports:
  - name: http
    port: 8008
    targetPort: 8008
  - name: https
    port: 8448
    targetPort: 8448
