apiVersion: v1
kind: PersistentVolume
metadata:
  name: synapse-server-pv
  namespace: matrix
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /home/files/.synapse/server
    server: 192.168.86.100
  storageClassName: synapse-server-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse-server-pvc
  namespace: matrix
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: synapse-server-pv
  storageClassName: synapse-server-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: synapse-psql-pv
  namespace: matrix
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /home/files/.synapse/postgres
    server: 192.168.86.100
  storageClassName: synapse-psql-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse-psql-pvc
  namespace: matrix
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: synapse-psql-pv
  storageClassName: synapse-psql-data
