apiVersion: v1
kind: PersistentVolume
metadata:
  name: synapse-server-pv
  namespace: matrix
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /srv/data/synapse/server
  storageClassName: synapse-server-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - server-master
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: synapse-psql-pv
  namespace: matrix
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /srv/data/synapse/postgres
  storageClassName: synapse-psql-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - server-master
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse-server-pvc
  namespace: matrix
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: synapse-server-pv
  storageClassName: synapse-server-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse-psql-pvc
  namespace: matrix
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: synapse-psql-pv
  storageClassName: synapse-psql-data
