apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv
  namespace: docker-registry
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /home/files/.docker-registry
    server: 192.168.86.100
  storageClassName: docker-registry
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
  namespace: docker-registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  volumeName: registry-pv
  storageClassName: docker-registry

