apiVersion: apps/v1
kind: Deployment
metadata:
  name: siyuan
  namespace: siyuan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: siyuan
  template:
    metadata:
      labels:
        app: siyuan
    spec:
      containers:
      - name: siyuan
        image: b3log/siyuan
        args: ["--workspace=/siyuan/workspace/", "--accessAuthCode=$(ACCESS_AUTH_CODE)"]
        ports:
        - containerPort: 6806
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: siyuan-config
              key: timezone
        - name: ACCESS_AUTH_CODE
          valueFrom:
            configMapKeyRef:
              name: siyuan-config
              key: accessAuthCode
        volumeMounts:
        - name: siyuan-workspace
          mountPath: /siyuan/workspace
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      volumes:
      - name: siyuan-workspace
        persistentVolumeClaim:
          claimName: siyuan-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: siyuan
  namespace: siyuan
spec:
  type: ClusterIP
  ports:
  - port: 6806
    targetPort: 6806
  selector:
    app: siyuan
