apiVersion: v1
kind: PersistentVolume
metadata:
  name: siyuan-pv
  namespace: siyuan
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /home/files/.siyuan
    server: 192.168.86.100
  storageClassName: siyuan-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: siyuan-pvc
  namespace: siyuan
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  volumeName: siyuan-pv
  storageClassName: siyuan-data
