apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: photos-ingress
  namespace: immich
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-body-size: "2G"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - photos.prayujt.com
    secretName: photos-ingress-tls
  rules:
  - host: photos.prayujt.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: immich-server
            port:
              number: 3001
