apiVersion: v1
kind: PersistentVolume
metadata:
  name: kratos-psql-pv
  namespace: kratos
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /home/files/.kratos
    server: 192.168.86.100
  storageClassName: kratos-psql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kratos-psql-pvc
  namespace: kratos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: kratos-psql-pv
  storageClassName: kratos-psql
