kratos:
  config:
    serve:
      public:
        base_url: https://idp.prayujt.com
    cookies:
      domain: prayujt.com
      same_site: None
    session:
      cookie:
        domain: prayujt.com
    dsn: postgres://kratos_user:kratos_password@postgres:5432/kratos_db
    identity:
      default_schema_id: default
      schemas:
        - id: default
          url: file:///etc/config/identity.default.schema.json
    selfservice:
      methods:
        password:
          enabled: true
      default_browser_return_url: https://login.prayujt.com/login
      flows:
        registration:
          ui_url: https://login.prayujt.com/register
    oauth2_provider:
      url: http://hydra-admin.hydra.svc.cluster.local:4445
    courier:
      smtp:
        connection_uri: "smtps://username:password@prayujt.com:465/?skip_ssl_verify=false"
  automigration:
    enabled: true
  identitySchemas:
    "identity.default.schema.json": |
      {
        "$id": "https://schemas.ory.sh/presets/kratos/identity.email.schema.json",
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "Person",
        "type": "object",
        "properties": {
          "traits": {
            "type": "object",
            "properties": {
              "email": {
                "type": "string",
                "format": "email",
                "title": "E-Mail",
                "ory.sh/kratos": {
                  "credentials": {
                    "password": {
                      "identifier": true
                    }
                  },
                  "recovery": {
                    "via": "email"
                  },
                  "verification": {
                    "via": "email"
                  }
                }
              },
              "username": {
                "type": "string",
                "title": "Username",
                "ory.sh/kratos": {
                  "credentials": {
                    "password": {
                      "identifier": true
                    }
                  }
                }
              },
              "firstName": {
                "type": "string",
                "title": "First Name"
              },
              "lastName": {
                "type": "string",
                "title": "Last Name"
              },
              "avatar": {
                "type": "string",
                "format": "uri",
                "title": "Avatar",
                "description": "A URL pointing to the location of the user's avatar"
              }
            },
            "required": [
              "email",
              "username",
              "firstName",
              "lastName"
            ],
            "additionalProperties": false
          }
        }
      }

