apiVersion: v1
kind: PersistentVolume
metadata:
  name: sync-psql-pv
  namespace: matrix
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /home/files/.synapse/sync-postgres
    server: 192.168.86.100
  storageClassName: sync-psql-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sync-psql-pvc
  namespace: matrix
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: sync-psql-pv
  storageClassName: sync-psql-data
