apiVersion: v1
kind: PersistentVolume
metadata:
  name: nimbus-db-pv
  namespace: nimbus
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /srv/nimbus/db
    server: 192.168.86.100
  storageClassName: nimbus-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nimbus-db-pvc
  namespace: nimbus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: nimbus-db-pv
  storageClassName: nimbus-db
