apiVersion: apps/v1
kind: Deployment
metadata:
  name: nimbus
  namespace: nimbus
  labels:
    app: nimbus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nimbus
  template:
    metadata:
      labels:
        app: nimbus
    spec:
      serviceAccountName: nimbus-sa
      containers:
        - name: nimbus
          image: docker.prayujt.com/nimbus
          ports:
            - containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: "production"
            - name: DOMAIN
              value: "prayujt.com"
            - name: DB_USER
              value: "nimbus"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: DB_HOST
              value: "nimbus-db"
            - name: DB_NAME
              value: "nimbus"
            - name: DB_PORT
              value: "5432"
            - name: NIMBUS_STORAGE_CLASS
              value: "nfs-client"
            - name: NIMBUS_PV
              value: "nfs-client"
          args:
            - "server"
---
apiVersion: v1
kind: Service
metadata:
  name: nimbus
  namespace: nimbus
  labels:
    app: nimbus
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: nimbus
  type: ClusterIP
