apiVersion: v1
kind: PersistentVolume
metadata:
  name: nimbus-data-pv
  namespace: nimbus
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /srv/nimbus/data
    server: 192.168.86.100
  storageClassName: nimbus-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nimbus-data-pvc
  namespace: nimbus
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: nimbus-data-pv
  storageClassName: nimbus-data
