apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vpn-ingress
  namespace: vpn
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      add_header Strict-Transport-Security "max-age=15552000; includeSubDomains" always;
spec:
  tls:
  - hosts:
    - vpn.prayujt.com
    secretName: vpn-prayujt-com-certs
  rules:
  - host: vpn.prayujt.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: headscale
            port:
              number: 8080

