apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
        - name: extract-nginx-config
          image: alpine
          command: ["sh", "-c", "tar -xzvf /etc/nginx-config/nginx-config.tar.gz -C /etc/nginx"]
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx
            - name: nginx-config-volume
              mountPath: /etc/nginx-config
      containers:
        - name: nginx-container
          image: nginx
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config

