apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  initContainers:
    - name: extract-nginx
      image: alpine
      command: ["sh", "-c", "tar -xzvf /etc/nginx-temp/nginx-config.tar.gz -C /etc/nginx; tar -xzvf /etc/letsencrypt-temp/nginx-certs.tar.gz -C /etc/letsencrypt; tar -xzvf /var/www/temp/prayujt-website.tar.gz -C /var/www/prayujt.com"]
      volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx
        - name: nginx-config-temp-volume
          mountPath: /etc/nginx-temp
        - name: nginx-certs-volume
          mountPath: /etc/letsencrypt
        - name: nginx-certs-temp-volume
          mountPath: /etc/letsencrypt-temp
        - name: prayujt-website-volume
          mountPath: /var/www/prayujt.com
        - name: prayujt-website-temp-volume
          mountPath: /var/www/temp
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx
        - name: nginx-certs-volume
          mountPath: /etc/letsencrypt
        - name: prayujt-website-volume
          mountPath: /var/www/prayujt.com
  volumes:
    - name: nginx-config-volume
      emptyDir: {}
    - name: nginx-certs-volume
      emptyDir: {}
    - name: prayujt-website-volume
      emptyDir: {}
    - name: nginx-config-temp-volume
      configMap:
        name: nginx-config
    - name: nginx-certs-temp-volume
      configMap:
        name: nginx-certs
    - name: prayujt-website-temp-volume
      configMap:
        name: prayujt-website
