apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        kubernetes.io/hostname: "server-master"
      initContainers:
        - name: extract-nginx
          image: alpine
          command: ["sh", "-c", "tar -xzvf /etc/nginx-temp/nginx-config.tar.gz -C /etc/nginx; tar -xzvf /etc/letsencrypt-temp/nginx-certs.tar.gz -C /etc/letsencrypt; tar -xzvf /var/www/temp/prayujt-website.tar.gz -C /var/www/prayujt.com"]
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx
            - name: nginx-config-temp-volume
              mountPath: /etc/nginx-temp
            - name: nginx-certs-volume
              mountPath: /etc/letsencrypt
            - name: nginx-certs-temp-volume
              mountPath: /etc/letsencrypt-temp
            - name: prayujt-website-volume
              mountPath: /var/www/prayujt.com
            - name: prayujt-website-temp-volume
              mountPath: /var/www/temp
      containers:
        - name: nginx-container
          image: ubuntu/nginx
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx
            - name: nginx-certs-volume
              mountPath: /etc/letsencrypt
            - name: prayujt-website-volume
              mountPath: /var/www/prayujt.com
            - name: prayujt-resume-volume
              mountPath: /var/www/prayujt.com/resume
      volumes:
        - name: nginx-config-volume
          emptyDir: {}
        - name: nginx-certs-volume
          emptyDir: {}
        - name: prayujt-website-volume
          emptyDir: {}
        - name: nginx-config-temp-volume
          configMap:
            name: nginx-config
        - name: nginx-certs-temp-volume
          configMap:
            name: nginx-certs
        - name: prayujt-website-temp-volume
          configMap:
            name: prayujt-website
        - name: prayujt-resume-volume
          persistentVolumeClaim:
            claimName: prayujt-resume

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx
spec:
  selector:
    app: nginx
  ports:
    - name: nginx-http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
    - name: nginx-ssl
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30001
    - name: nginx-ssh
      protocol: TCP
      port: 22
      targetPort: 22
      nodePort: 30002
  type: NodePort

