apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailserver
  template:
    metadata:
      labels:
        app: mailserver
    spec:
      nodeSelector:
        kubernetes.io/hostname: "server-master"
      hostNetwork: true
      containers:
      - name: mailserver
        image: ghcr.io/docker-mailserver/docker-mailserver:latest
        ports:
        - containerPort: 25
        - containerPort: 143
        - containerPort: 465
        - containerPort: 587
        - containerPort: 993
        env:
        - name: SSL_TYPE
          value: "manual"
        - name: SSL_CERT_PATH
          value: "/certs/tls.crt"
        - name: SSL_KEY_PATH
          value: "/certs/tls.key"
        - name: LOG_LEVEL
          value: "trace"
        - name: POSTMASTER_ADDRESS
          value: "postmaster@prayujt.com"
        - name: LDAP_START_TLS
          value: "yes"
        - name: LDAP_SERVER_HOST
          value: "ldaps://mail.prayujt.com"
        - name: OVERRIDE_HOSTNAME
          value: "mail.prayujt.com"
        - name: LETSENCRYPT_DOMAIN
          value: "mail.prayujt.com"
        - name: POSTFIX_REJECT_UNKNOWN_CLIENT_HOSTNAME
          value: "1"
        - name: PERMIT_DOCKER
          value: "none"
        - name: TLS_LEVEL
          value: "intermediate"
        volumeMounts:
        - name: mail-data
          mountPath: "/var/mail/"
        - name: mail-state
          mountPath: "/var/mail-state/"
        - name: mail-logs
          mountPath: "/var/log/mail/"
        - name: config
          mountPath: "/tmp/docker-mailserver/"
        - name: tls-secret
          mountPath: "/certs"
        - name: localtime
          mountPath: "/etc/localtime"
          readOnly: true
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
          initialDelaySeconds: 10
          timeoutSeconds: 3
          failureThreshold: 1
      volumes:
      - name: mail-data
        hostPath:
          path: /root/kubeconfigs/mailserver/docker-data/dms/mail-data/
      - name: mail-state
        hostPath:
          path: /root/kubeconfigs/mailserver/docker-data/dms/mail-state/
      - name: mail-logs
        hostPath:
          path: /root/kubeconfigs/mailserver/docker-data/dms/mail-logs/
      - name: config
        hostPath:
          path: /root/kubeconfigs/mailserver/docker-data/dms/config/
      - name: tls-secret
        secret:
          secretName: mail-prayujt-tls
      - name: localtime
        hostPath:
          path: /etc/localtime
---
apiVersion: v1
kind: Service
metadata:
  name: mailserver-service
spec:
  type: NodePort
  selector:
    app: mailserver
  ports:
    - name: smtp
      protocol: TCP
      port: 25
      targetPort: 25
      nodePort: 10000
    - name: imap
      protocol: TCP
      port: 143
      targetPort: 143
      nodePort: 10001
    - name: esmtp-implicit-tls
      protocol: TCP
      port: 465
      targetPort: 465
      nodePort: 10002
    - name: esmtp-explicit-tls
      protocol: TCP
      port: 587
      targetPort: 587
      nodePort: 10003
    - name: imap4-implicit-tls
      protocol: TCP
      port: 993
      targetPort: 993
      nodePort: 10004
