apiVersion: v1
kind: PersistentVolume
metadata:
  name: turn-server-pv
  namespace: matrix
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /srv/data/synapse/turn
  storageClassName: turn-server-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - server-master
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: turn-server-pvc
  namespace: matrix
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  volumeName: turn-server-pv
  storageClassName: turn-server-config
