apiVersion: v1
kind: PersistentVolume
metadata:
  name: outline-nfs-pv-https-portal
  namespace: outline
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /home/files/.outline-data/https-portal
    server: 192.168.86.100
  storageClassName: outline-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: outline-nfs-pv-storage
  namespace: outline
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /home/files/.outline-data/storage
    server: 192.168.86.100
  storageClassName: outline-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: outline-nfs-pv-redis
  namespace: outline
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /home/files/.outline-data/redis
    server: 192.168.86.100
  storageClassName: outline-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: outline-nfs-pv-postgres
  namespace: outline
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /home/files/.outline-data/postgres
    server: 192.168.86.100
  storageClassName: outline-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: outline-https-portal
  namespace: outline
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  volumeName: outline-nfs-pv-https-portal
  storageClassName: outline-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: outline-storage
  namespace: outline
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  volumeName: outline-nfs-pv-storage
  storageClassName: outline-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: outline-redis
  namespace: outline
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: outline-nfs-pv-redis
  storageClassName: outline-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: outline-postgres
  namespace: outline
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  volumeName: outline-nfs-pv-postgres
  storageClassName: outline-data

