#!/bin/bash

# Check if the correct number of arguments was passed
if [ "$#" -ne 2 ]; then
  echo "Usage: $0 <secret-name> <domain-name>"
  exit 1
fi

SECRET_NAME=$1
DOMAIN_NAME=$2
NAMESPACE=$3

# Define the paths to the certificate and key files
CERT_PATH="/etc/letsencrypt/live/${DOMAIN_NAME}/fullchain.pem"
KEY_PATH="/etc/letsencrypt/live/${DOMAIN_NAME}/privkey.pem"

# Check if the certificate and key files exist
if [ ! -f "$CERT_PATH" ] || [ ! -f "$KEY_PATH" ]; then
  echo "Certificate or key file does not exist."
  exit 1
fi

# Create the secret and output it to a YAML file
kubectl create secret tls "${SECRET_NAME}-ingress-tls" \
  --cert=$CERT_PATH \
  --key=$KEY_PATH \
  --namespace=$NAMESPACE

echo "TLS secret created"
