apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  22: "gitea/gitea-ssh:2222"
  6379: "edugator/redis:6379"
  5432: "cloud/postgres-public:5432"
  5433: "hydrogator/postgres:5432"
