apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-nginx-config
  namespace: static
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /srv/data/static/config
  storageClassName: static-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - server-master
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-nginx-content
  namespace: static
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /srv/data/static/content
  storageClassName: static-content
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - server-master
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-nginx-config
  namespace: static
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  volumeName: static-nginx-config
  storageClassName: static-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-nginx-content
  namespace: static
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: static-nginx-content
  storageClassName: static-content
