apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: local-network
      protocol: layer2
      addresses:
      - 192.168.86.100-192.168.86.105
