apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin-ingress
  namespace: jellyfin
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 2g
    cert-manager.io/cluster-issuer: letsencrypt-prod

    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Forwarded-For $http_x_forwarded_for";

      #nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
      #nginx.ingress.kubernetes.io/real-ip-header: "X-Forwarded-For"
spec:
  tls:
  - hosts:
    - tv.prayujt.com
    secretName: tv-prayujt-certs
  rules:
  - host: tv.prayujt.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jellyfin
            port:
              number: 8096
