apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config
  namespace: jellyfin
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /home/files/.jellyfin/config
    server: 192.168.86.100
  storageClassName: jellyfin-config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-cache
  namespace: jellyfin
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /home/files/.jellyfin/cache
    server: 192.168.86.100
  storageClassName: jellyfin-cache
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media
  namespace: jellyfin
spec:
  capacity:
    storage: 450Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /srv/media
    server: 192.168.86.100
  storageClassName: jellyfin-media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: jellyfin-config
  storageClassName: jellyfin-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: jellyfin-cache
  storageClassName: jellyfin-cache
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 450Gi
  volumeName: jellyfin-media
  storageClassName: jellyfin-media
