apiVersion: v1
kind: PersistentVolume
metadata:
  name: audio-scraper-music
  namespace: audio-scraper
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /srv/music
  storageClassName: audio-scraper-music
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - server-master
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audio-scraper-music-pvc
  namespace: audio-scraper
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  volumeName: audio-scraper-music
  storageClassName: audio-scraper-music
