apiVersion: v1
kind: PersistentVolume
metadata:
  name: audio-scraper-music
  namespace: audio-scraper
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /srv/music
    server: 192.168.86.100
  storageClassName: audio-scraper-music
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audio-scraper-music-pvc
  namespace: audio-scraper
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  volumeName: audio-scraper-music
  storageClassName: audio-scraper-music
