apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghost-content-pv
  namespace: ghost
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /srv/data/ghost/content
  storageClassName: ghost-content
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - server-master
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghost-mysql-pv
  namespace: ghost
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /srv/data/ghost/db
  storageClassName: ghost-mysql
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - server-master
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-content-pvc
  namespace: ghost
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: ghost-content-pv
  storageClassName: ghost-content
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-mysql-pvc
  namespace: ghost
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: ghost-mysql-pv
  storageClassName: ghost-mysql
