apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghost-content-pv
  namespace: ghost
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /home/files/.ghost/content
    server: 192.168.86.100
  storageClassName: ghost-content
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghost-mysql-pv
  namespace: ghost
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /home/files/.ghost/db
    server: 192.168.86.100
  storageClassName: ghost-mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-content-pvc
  namespace: ghost
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: ghost-content-pv
  storageClassName: ghost-content
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-mysql-pvc
  namespace: ghost
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: ghost-mysql-pv
  storageClassName: ghost-mysql
