apiVersion: v1
kind: Secret
metadata:
  name: affine-admin-secret
  namespace: affine
type: Opaque
stringData:
  email: "admin@example.com"  # Replace with actual email
  password: "adminpassword"   # Replace with actual password

---
apiVersion: v1
kind: Secret
metadata:
  name: affine-mailer-secret
  namespace: affine
type: Opaque
stringData:
  host: "mailer.example.com"  # Replace with actual host
  port: "587"                 # Replace with actual port
  email: "mailer@example.com" # Replace with actual email
  sender: "noreply@example.com" # Replace with actual sender
  password: "mailerpassword"  # Replace with actual password

