apiVersion: v1
kind: PersistentVolume
metadata:
  name: affine-nfs-pv-config
  namespace: affine
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /srv/data/affine/config
    server: 192.168.86.100
  storageClassName: affine-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: affine-nfs-pv-storage
  namespace: affine
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /srv/data/affine/storage
    server: 192.168.86.100
  storageClassName: affine-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: affine-nfs-pv-redis
  namespace: affine
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /srv/data/affine/redis
    server: 192.168.86.100
  storageClassName: affine-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: affine-nfs-pv-postgres
  namespace: affine
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /srv/data/affine/postgres
    server: 192.168.86.100
  storageClassName: affine-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: affine-config
  namespace: affine
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: affine-nfs-pv-config
  storageClassName: affine-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: affine-storage
  namespace: affine
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: affine-nfs-pv-storage
  storageClassName: affine-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: affine-redis
  namespace: affine
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: affine-nfs-pv-redis
  storageClassName: affine-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: affine-postgres
  namespace: affine
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  volumeName: affine-nfs-pv-postgres
  storageClassName: affine-data

