apiVersion: v1
kind: PersistentVolume
metadata:
  name: syncthing-nfs-pv
  namespace: syncthing
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /srv/sync
    server: 192.168.86.100
  storageClassName: syncthing
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-nfs-pvc
  namespace: syncthing
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  volumeName: syncthing-nfs-pv
  storageClassName: syncthing

