apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-streaming-service-account
  namespace: kube-streaming
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kube-streaming
  name: job-manager
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "delete", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-manager-binding
  namespace: kube-streaming
subjects:
- kind: ServiceAccount
  name: kube-streaming-service-account
  namespace: kube-streaming
roleRef:
  kind: Role
  name: job-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-streaming
  namespace: kube-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-streaming
  template:
    metadata:
      labels:
        app: kube-streaming
    spec:
      serviceAccountName: kube-streaming-service-account
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
      - name: kube-streaming
        image: docker.prayujt.com/kube-streaming-api
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: kube-streaming-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: kube-streaming
  namespace: kube-streaming
spec:
  type: ClusterIP
  selector:
    app: kube-streaming
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

